#!/bin/bash

# table_5.5.1_n_1000.taocp.sh

# generates data of 1000 values used in table 1 from section 5.5 of taocp vol 3
# data is generated by the formula:
#  K_1001 = 0
#  K_(n-1) = (3141592621 * K_n + 2113148651) mod 10^10, for n = 1001,...,2

# numbers are too big for bash, use bc or awk

bc <<EOF

# insure integer mod
scale = 0

ten_10 = 10^10

k[1001] = 0
for(n = 1001; n >= 2; --n) {
  k[n - 1] = (3141592621 * k[n] + 2113148651) % ten_10
}

for(i = 1; i <= 1000; ++i) {
  print k[i], "\n"
}

EOF

